CREATE DATABASE IF NOT EXISTS catalog_maker CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE catalog_maker;

CREATE TABLE IF NOT EXISTS catalog_config (id TINYINT PRIMARY KEY DEFAULT 1, client_name VARCHAR(160) NOT NULL, whatsapp_number VARCHAR(30) NOT NULL, active_design VARCHAR(32) NOT NULL DEFAULT 'editorial', revision BIGINT NOT NULL DEFAULT 1, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categories (id CHAR(36) PRIMARY KEY, slug VARCHAR(180) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, sort_order INT NOT NULL DEFAULT 0, visible BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS products (id CHAR(36) PRIMARY KEY, source VARCHAR(40) NOT NULL DEFAULT 'manual', source_id VARCHAR(255) NULL, source_url TEXT NULL, name VARCHAR(500) NOT NULL, sku VARCHAR(255) NULL, price DECIMAL(12,2) NOT NULL DEFAULT 0, compare_at_price DECIMAL(12,2) NULL, currency CHAR(3) NOT NULL DEFAULT 'INR', description TEXT NOT NULL, category_id CHAR(36) NULL, stock INT NOT NULL DEFAULT 0, metadata JSON NOT NULL, source_fingerprint CHAR(64) NULL, source_updated_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY products_source_unique (source, source_id), KEY products_category_idx (category_id), KEY products_updated_idx (updated_at), FULLTEXT KEY products_search_idx (name, sku, description), CONSTRAINT products_category_fk FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS product_images (id CHAR(36) PRIMARY KEY, product_id CHAR(36) NOT NULL, url TEXT NOT NULL, alt_text VARCHAR(500) NULL, position INT NOT NULL DEFAULT 0, width INT NULL, height INT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY product_images_product_idx (product_id), CONSTRAINT product_images_product_fk FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS product_variants (id CHAR(36) PRIMARY KEY, product_id CHAR(36) NOT NULL, source_id VARCHAR(255) NULL, title VARCHAR(255) NOT NULL, sku VARCHAR(255) NULL, price DECIMAL(12,2) NULL, stock INT NULL, options JSON NOT NULL, UNIQUE KEY variants_source_unique (product_id, source_id), CONSTRAINT variants_product_fk FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS sync_runs (id CHAR(36) PRIMARY KEY, source VARCHAR(40) NOT NULL, status VARCHAR(40) NOT NULL, started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, finished_at DATETIME NULL, created_count INT NOT NULL DEFAULT 0, updated_count INT NOT NULL DEFAULT 0, unchanged_count INT NOT NULL DEFAULT 0, error_count INT NOT NULL DEFAULT 0, summary JSON NOT NULL);
CREATE TABLE IF NOT EXISTS sync_errors (id CHAR(36) PRIMARY KEY, sync_run_id CHAR(36) NOT NULL, source_product_id VARCHAR(255) NULL, stage VARCHAR(80) NOT NULL, message TEXT NOT NULL, details JSON NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY sync_errors_run_idx (sync_run_id), CONSTRAINT sync_errors_run_fk FOREIGN KEY (sync_run_id) REFERENCES sync_runs(id) ON DELETE CASCADE);
